/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookingPolicyRouteImport } from './routes/booking-policy'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSeamlessClipInsRouteImport } from './routes/shop.seamless-clip-ins'
import { Route as ShopHairAccessoriesRouteImport } from './routes/shop.hair-accessories'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPolicyRoute = BookingPolicyRouteImport.update({
  id: '/booking-policy',
  path: '/booking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSeamlessClipInsRoute = ShopSeamlessClipInsRouteImport.update({
  id: '/seamless-clip-ins',
  path: '/seamless-clip-ins',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHairAccessoriesRoute = ShopHairAccessoriesRouteImport.update({
  id: '/hair-accessories',
  path: '/hair-accessories',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/shop/hair-accessories': typeof ShopHairAccessoriesRoute
  '/shop/seamless-clip-ins': typeof ShopSeamlessClipInsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/shop/hair-accessories': typeof ShopHairAccessoriesRoute
  '/shop/seamless-clip-ins': typeof ShopSeamlessClipInsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/lookbook': typeof LookbookRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/shop/hair-accessories': typeof ShopHairAccessoriesRoute
  '/shop/seamless-clip-ins': typeof ShopSeamlessClipInsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/booking-policy'
    | '/checkout'
    | '/contact'
    | '/health'
    | '/lookbook'
    | '/policies'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/shop/hair-accessories'
    | '/shop/seamless-clip-ins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking'
    | '/booking-policy'
    | '/checkout'
    | '/contact'
    | '/health'
    | '/lookbook'
    | '/policies'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/shop/hair-accessories'
    | '/shop/seamless-clip-ins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/booking-policy'
    | '/checkout'
    | '/contact'
    | '/health'
    | '/lookbook'
    | '/policies'
    | '/services'
    | '/shop'
    | '/sitemap.xml'
    | '/shop/hair-accessories'
    | '/shop/seamless-clip-ins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  BookingPolicyRoute: typeof BookingPolicyRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HealthRoute: typeof HealthRoute
  LookbookRoute: typeof LookbookRoute
  PoliciesRoute: typeof PoliciesRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-policy': {
      id: '/booking-policy'
      path: '/booking-policy'
      fullPath: '/booking-policy'
      preLoaderRoute: typeof BookingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/seamless-clip-ins': {
      id: '/shop/seamless-clip-ins'
      path: '/seamless-clip-ins'
      fullPath: '/shop/seamless-clip-ins'
      preLoaderRoute: typeof ShopSeamlessClipInsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/hair-accessories': {
      id: '/shop/hair-accessories'
      path: '/hair-accessories'
      fullPath: '/shop/hair-accessories'
      preLoaderRoute: typeof ShopHairAccessoriesRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopHairAccessoriesRoute: typeof ShopHairAccessoriesRoute
  ShopSeamlessClipInsRoute: typeof ShopSeamlessClipInsRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopHairAccessoriesRoute: ShopHairAccessoriesRoute,
  ShopSeamlessClipInsRoute: ShopSeamlessClipInsRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  BookingPolicyRoute: BookingPolicyRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HealthRoute: HealthRoute,
  LookbookRoute: LookbookRoute,
  PoliciesRoute: PoliciesRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
